# Site settings
title: "CircleCI Documentation"
email: docs@cirleci.com
description: > # this means to ignore newlines until "baseurl:"
  The documentation site for CircleCI, the fastest testing platform on the 
  Internet.

url: "http://localhost:4040" # the base hostname & protocol for your site
baseurl: "/docs" # the subpath of your site, e.g. /blog
gh_url: "https://github.com/circleci/circleci-docs"

markdown: kramdown
kramdown:
  input: GFM

collections:
  docs:
    output: true
    permalink: /:path/
  cci2:
    output: true
    permalink: /2.0/:path/
    prefix: 2.0
    categories:
      - overview: "Overview"
      - getting-started: "Getting Started"
      - language-guides: "Language Guides"
      - configuring-circleci: "Configuring CircleCI"
      - reference: "Reference"

twitter_username: circleci
github_username:  circleci

defaults:
  -
    scope:
      path: ""
    values:
      hide: false
      section: cci1

segment: 'mAJ9W2SwLHgmJtFkpaXWCbwEeNk9D8CZ'
